
CREATE TABLE IF NOT EXISTS tables (
    name TEXT,
    catalog_name TEXT,
    schema_name TEXT,
    table_type TEXT,
    data_source_format TEXT,
    storage_location TEXT,
    view_definition TEXT,
    sql_path TEXT,
    owner TEXT,
    comment TEXT,
    storage_credential_name TEXT,
    enable_predictive_optimization TEXT,
    metastore_id TEXT,
    full_name TEXT,
    data_access_configuration_id TEXT,
    created_at INTEGER,
    created_by TEXT,
    updated_at INTEGER,
    updated_by TEXT,
    deleted_at INTEGER,
    table_id TEXT,
    access_point TEXT,
    pipeline_id TEXT,
    browse_only BOOLEAN--,
    -- PRIMARY KEY (name, catalog_name, schema_name),
    -- FOREIGN KEY (catalog_name) REFERENCES Catalog(name),
    -- FOREIGN KEY (schema_name, catalog_name) REFERENCES Schema(name, catalog_name)
);